---
name: renovate
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run renovate
        uses: renovatebot/github-action@v41.0.16
        continue-on-error: true
        env:
          RENOVATE_REPOSITORIES: "Comcast/scte35-go"
        with:
          configurationFile: ./.github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
